# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b28ab782f3ea0a252f0cbb2489f4f6c4844d69ff17b9c9ded5eb65cbe53730a60b5116e0858211d31b38a42d32d8a408903e4406662edd0501152923027d4c9f

test:
  secret_key_base: a264c9fbc33b59f85f5754b9abbaf007ce9b669c5fc0874fcda8c954903c2cf0dce872cc24fab87d3f717f71d88b754e4cbacec55333af45f016eb85e9f2f345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
